name: kelola
description: Agentless Linux server administration from a phone.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  drift: ^2.28.1
  drift_flutter: ^0.2.4
  dartssh2: ^3.3.1
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  path: ^1.9.1
  path_provider: ^2.1.5
  collection: ^1.19.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
